/*
 * This file is generated by jOOQ.
 */
package ru.mai.lessons.rpks.jooq.model.tables.records;


import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record6;
import org.jooq.Row6;
import org.jooq.impl.UpdatableRecordImpl;

import ru.mai.lessons.rpks.jooq.model.tables.FilterRules;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class FilterRulesRecord extends UpdatableRecordImpl<FilterRulesRecord> implements Record6<Integer, Long, Long, String, String, String> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.filter_rules.id</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.filter_rules.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>public.filter_rules.filter_id</code>.
     */
    public void setFilterId(Long value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.filter_rules.filter_id</code>.
     */
    public Long getFilterId() {
        return (Long) get(1);
    }

    /**
     * Setter for <code>public.filter_rules.rule_id</code>.
     */
    public void setRuleId(Long value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.filter_rules.rule_id</code>.
     */
    public Long getRuleId() {
        return (Long) get(2);
    }

    /**
     * Setter for <code>public.filter_rules.field_name</code>.
     */
    public void setFieldName(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.filter_rules.field_name</code>.
     */
    public String getFieldName() {
        return (String) get(3);
    }

    /**
     * Setter for <code>public.filter_rules.filter_function_name</code>.
     */
    public void setFilterFunctionName(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>public.filter_rules.filter_function_name</code>.
     */
    public String getFilterFunctionName() {
        return (String) get(4);
    }

    /**
     * Setter for <code>public.filter_rules.filter_value</code>.
     */
    public void setFilterValue(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>public.filter_rules.filter_value</code>.
     */
    public String getFilterValue() {
        return (String) get(5);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record6 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row6<Integer, Long, Long, String, String, String> fieldsRow() {
        return (Row6) super.fieldsRow();
    }

    @Override
    public Row6<Integer, Long, Long, String, String, String> valuesRow() {
        return (Row6) super.valuesRow();
    }

    @Override
    public Field<Integer> field1() {
        return FilterRules.FILTER_RULES.ID;
    }

    @Override
    public Field<Long> field2() {
        return FilterRules.FILTER_RULES.FILTER_ID;
    }

    @Override
    public Field<Long> field3() {
        return FilterRules.FILTER_RULES.RULE_ID;
    }

    @Override
    public Field<String> field4() {
        return FilterRules.FILTER_RULES.FIELD_NAME;
    }

    @Override
    public Field<String> field5() {
        return FilterRules.FILTER_RULES.FILTER_FUNCTION_NAME;
    }

    @Override
    public Field<String> field6() {
        return FilterRules.FILTER_RULES.FILTER_VALUE;
    }

    @Override
    public Integer component1() {
        return getId();
    }

    @Override
    public Long component2() {
        return getFilterId();
    }

    @Override
    public Long component3() {
        return getRuleId();
    }

    @Override
    public String component4() {
        return getFieldName();
    }

    @Override
    public String component5() {
        return getFilterFunctionName();
    }

    @Override
    public String component6() {
        return getFilterValue();
    }

    @Override
    public Integer value1() {
        return getId();
    }

    @Override
    public Long value2() {
        return getFilterId();
    }

    @Override
    public Long value3() {
        return getRuleId();
    }

    @Override
    public String value4() {
        return getFieldName();
    }

    @Override
    public String value5() {
        return getFilterFunctionName();
    }

    @Override
    public String value6() {
        return getFilterValue();
    }

    @Override
    public FilterRulesRecord value1(Integer value) {
        setId(value);
        return this;
    }

    @Override
    public FilterRulesRecord value2(Long value) {
        setFilterId(value);
        return this;
    }

    @Override
    public FilterRulesRecord value3(Long value) {
        setRuleId(value);
        return this;
    }

    @Override
    public FilterRulesRecord value4(String value) {
        setFieldName(value);
        return this;
    }

    @Override
    public FilterRulesRecord value5(String value) {
        setFilterFunctionName(value);
        return this;
    }

    @Override
    public FilterRulesRecord value6(String value) {
        setFilterValue(value);
        return this;
    }

    @Override
    public FilterRulesRecord values(Integer value1, Long value2, Long value3, String value4, String value5, String value6) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached FilterRulesRecord
     */
    public FilterRulesRecord() {
        super(FilterRules.FILTER_RULES);
    }

    /**
     * Create a detached, initialised FilterRulesRecord
     */
    public FilterRulesRecord(Integer id, Long filterId, Long ruleId, String fieldName, String filterFunctionName, String filterValue) {
        super(FilterRules.FILTER_RULES);

        setId(id);
        setFilterId(filterId);
        setRuleId(ruleId);
        setFieldName(fieldName);
        setFilterFunctionName(filterFunctionName);
        setFilterValue(filterValue);
    }
}
