/*
 * This file is generated by jOOQ.
 */
package ru.mai.lessons.rpks.jooq.model;


import ru.mai.lessons.rpks.jooq.model.tables.FilterRules;


/**
 * Convenience access to all tables in public.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>public.filter_rules</code>.
     */
    public static final FilterRules FILTER_RULES = FilterRules.FILTER_RULES;
}
